import vm from 'node:vm';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const prefs = {};
const context = vm.createContext({MProvider: class {}, Client: class {async post(url,headers,body) {assert.equal(typeof body,"object","Mangayomi JSON POST requires an object, not an encoded string");const r=await fetch(url,{method:"POST",headers,body:JSON.stringify(body)});if(!r.ok) throw Error("HTTP "+r.status);return {body:await r.text()};} async get(url) {const r=await fetch(url); if(!r.ok) throw Error('HTTP '+r.status);return {body:await r.text()};}}, assert, SharedPreferences:class {get(k){return prefs[k];}},console});
vm.runInContext(readFileSync(new URL('../anime/src/all/stremiobridge.js',import.meta.url),'utf8')+'\nglobalThis.provider=new DefaultExtension();',context);
const p=context.provider;
const m={id:16498,idMal:16498,title:{romaji:'Season 2'},coverImage:{large:'poster'},status:'FINISHED',format:'TV',episodes:12};
const eps=p.anilistEpisodes(m);
assert.equal(eps.length,12);assert.equal(eps[0].name,'Episode 12');assert.equal(eps[11].name,'Episode 1');
assert.equal(p.unpackRef(eps[11].url).id,'mal:16498:1');
assert.equal(p.anilistItem(m).link,p.anilistItem({...m,idMal:99,title:{romaji:'Changed'}}).link);
assert.notEqual(p.anilistItem(m).link,p.anilistItem({...m,id:99}).link);
assert.equal(p.anilistEpisodes({...m,status:'RELEASING',nextAiringEpisode:{episode:4}}).length,3);
assert.equal(p.anilistEpisodes({...m,status:'NOT_YET_RELEASED'}).length,0);
assert.equal(p.anilistEpisodes({...m,episodes:null}).length,0);
assert.equal(p.anilistEpisodes({...m,nextAiringEpisode:{episode:1}}).length,0);
assert.equal(p.anilistEpisodes({...m,format:'MOVIE',episodes:1})[0].name,'Episode 1');
assert.equal(p.unpackRef(p.anilistEpisodes({...m,format:'MOVIE',episodes:1})[0].url).id,'mal:16498');
assert.throws(()=>p.anilistEpisodes({...m,idMal:null}),/MAL/);
await assert.rejects(()=>p.getDetail(p.packRef({kind:'meta',id:'tt123'})),/AniList/);
await assert.rejects(()=>p.getVideoList(p.packRef({kind:'stream',id:'tt123:2:1'})),/AniList/);
assert(!p.getSourcePreferences().some(x=>/catalog/.test(x.key)));
const original=p.requestJson.bind(p);const requested=[];
prefs.stremio_stream_manifest_urls='https://example.com/config/manifest.json';
p.requestJson=async url=>{requested.push(url);return url.endsWith('manifest.json')?{resources:['stream']}:{streams:[{url:'https://example.com/video.mp4'}]};};
assert.equal((await p.getVideoList(eps[11].url)).length,1);
assert.deepEqual(requested, ['https://example.com/config/manifest.json', 'https://example.com/config/stream/series/mal:16498:1.json']);
p.requestJson=original;
console.log('PASS: separate stable titles, local numbering, aired episodes, movies, missing mappings, legacy rejection, MAL stream routing.');
if(process.argv.includes('--live')) {
 const result=await p.search((await p.getDetail(p.packRef({kind:'anilist',id:20958}))).name,1,[]);
 assert(result.list.length>1);
 const season=result.list.find(x=>p.unpackRef(x.link).id===20958);assert(season);
 const detail=await p.getDetail(season.link);assert.equal(detail.episodes.length,12);
 const first=detail.episodes.at(-1);assert.equal(first.name,'Episode 1');assert.equal(p.unpackRef(first.url).id,'mal:25777:1');
 const otherEntry=await p.getDetail(p.packRef({kind:'anilist',id:104276}));
 assert.equal(otherEntry.episodes.length,25);
 assert.equal(otherEntry.episodes.at(-1).name,'Episode 1');
 assert.equal(p.unpackRef(otherEntry.episodes.at(-1).url).id,'mal:38408:1');
 console.log('PASS live: mapped anime entry -> 25 episodes -> mal:38408:1');
 console.log('PASS live: AniList search -> mapped anime entry -> 12 episodes -> mal:25777:1');
}

assert.equal(p.streamQuality({name:"AIO 1080p",description:"Release title"},"AIOStreams","https://example.com/2160p.mp4"),"AIO 1080p - Release title - [AIOStreams]");
assert.equal(p.streamQuality({name:"Original name"},"","https://example.com/1080p.mp4"),"Original name");
console.log("PASS: source names preserve AIOStreams resolution without adding a prefix.");
const savedRequest=p.requestJson.bind(p);
const requests=[];
p.manifestCache={};
p.requestJson=async url=>{
 requests.push(url);
 if(url.endsWith('/manifest.json'))return {resources:['stream',{name:'subtitles',types:['series'],idPrefixes:['tt']}]};
 if(url.includes('/api/v1/anime'))return {data:{mappings:{imdbId:'tt123'},imdb:{seasonNumber:2,fromEpisode:13}}};
 if(url.includes('/subtitles/'))return {subtitles:[{url:'https://example.com/sub.srt',lang:'en',subtitleFileName:'Release-A.srt'},null,{url:'file:///private/sub.srt'}]};
 return {streams:[{url:'https://example.com/a.mp4',subtitles:[{url:'https://example.com/sub.srt',lang:'en',subtitleFileName:'Release-A.srt'}]},{url:'https://example.com/b.mp4'}]};
};
const withSubs=await p.getVideoList(eps.at(-1).url);
assert.equal(withSubs.length,2);
for(const v of withSubs){assert.equal(v.subtitles.length,1);assert.equal(v.subtitles[0].label,'en — Release-A.srt');assert.equal(v.subtitles[0].file,'https://example.com/sub.srt');}
assert(requests.includes('https://example.com/config/subtitles/series/tt123:2:13.json'));
const workingRequest=p.requestJson;
p.requestJson=async url=>{if(url.includes('/subtitles/'))throw Error('Unavailable');return workingRequest(url);};
const withoutLookup=await p.getVideoList(eps.at(-1).url);
assert.equal(withoutLookup.length,2);assert.equal(withoutLookup[0].subtitles.length,1);assert.equal(withoutLookup[1].subtitles.length,0);
p.requestJson=savedRequest;
console.log('PASS: Source subtitles, release labels, deduplication, episode offset and playback when subtitle lookup fails.');
